function escadastro() {
  var $xy = document.querySelector('.conteudo_central'),
  t='<div class="xy">',
  t=t+'<div id="tabelacad">',
  t=t+'<h1>Cadastro Cliente</h1>',
  t=t+'<form>',
  t=t+'Seu nome: <br>',
  t=t+'<input type="text" name="primeironomecad" required> <br>',
  t=t+'Seu sobrenome: <br>',
  t=t+'<input type="text" name="sobrenomecad" required> <br>',
  t=t+'Seu e-mail: <br>',
  t=t+'<input type="text" name="emailcad" placeholder="Ex.: ricardo@gmail.com" required> <br>',
  t=t+'Seu CEP: <br>',
  t=t+'<input type="number" name="cepcad" placeholder="xxxxx-xxx" required> <br>',
  t=t+'Seu telefone de contato: <br>',
  t=t+'<input type="number" name="telcad" placeholder="(xx) x xxxx-xxxx" required> <br>',
  t=t+'Tipo de cadastro:<br>',
  t=t+'<input list="tipo" required><datalist id="tipo">',
  t=t+'<option value="Cliente">Cliente</option>',
  t=t+'<option value="Servidor">Servidor</option>',
  t=t+'</datalist><br>',
  t=t+'Crie uma senha: <br>',
  t=t+'<input type="password" name="senhacad" required> <br>',
  t=t+'Confirme sua senha: <br>',
  t=t+'<input type="password" name="confirmasenhacad" required><br><br>',
  t=t+'<input type="submit" value="Me cadastrar">',
  t=t+'</form>',
  t=t+'</div>',
  t=t+'<div id="tabelacadE">',
  t=t+'<h1>Cadastro Equipe Hype</h1>',
  t=t+'<form>',
  t=t+'Seu nome: <br>',
  t=t+'<input type="text" name="primeironomecad" required> <br>',
  t=t+'Seu sobrenome: <br>',
  t=t+'<input type="text" name="sobrenomecad" required> <br>',
  t=t+'Seu e-mail: <br>',
  t=t+'<input type="text" name="emailcad" placeholder="Ex.: ricardo@gmail.com" required> <br>',
  t=t+'Seu CEP: <br>',
  t=t+'<input type="number" name="cepcad" placeholder="xxxxx-xxx" required> <br>',
  t=t+'Seu telefone de contato: <br>',
  t=t+'<input type="number" name="telcad" placeholder="(xx) x xxxx-xxxx" required> <br>',
  t=t+'Tipo de cadastro:<br>',
  t=t+'<input list="tipo" required><datalist id="tipo">',
  t=t+'<option value="Cliente">Cliente</option>',
  t=t+'<option value="Servidor">Servidor</option>',
  t=t+'</datalist><br>',
  t=t+'Crie uma senha: <br>',
  t=t+'<input type="password" name="senhacad" required> <br>',
  t=t+'Confirme sua senha: <br>',
  t=t+'<input type="password" name="confirmasenhacad" required><br><br>',
  t=t+'<input type="submit" value="Me cadastrar">',
  t=t+'</form>',
  t=t+'</div>',
  t=t+'</div>'
$xy.innerHTML=t;
};
