function escadastro() {
  var $xy = document.querySelector('.conteudo_central'),
  t='<div class="xy">',
  t=t+'<div id="tabelacad">',
  t=t+'<h1>Cliente</h1>',
  t=t+'<form onsubmit="return cadastrar();">',
  t=t+'Seu nome: <br>',
  t=t+'<input type="text" name="primeironomecad" id="nome" required> <br>',
  t=t+'Seu sobrenome: <br>',
  t=t+'<input type="text" name="sobrenomecad" required> <br>',
  t=t+'Seu e-mail: <br>',
  t=t+'<input type="text" name="emailcad" placeholder="Ex.: ricardo@gmail.com" required> <br>',
  t=t+'Seu CEP: <br>',
  t=t+'<input type="number" name="cepcad" placeholder="xxxxx-xxx" required> <br>',
  t=t+'Seu telefone de contato: <br>',
  t=t+'<input type="number" name="telcad" placeholder="(xx) x xxxx-xxxx" required> <br>',
  t=t+'</datalist><br>',
  t=t+'Crie uma senha: <br>',
  t=t+'<input type="password" name="senhacad" required> <br>',
  t=t+'Confirme sua senha: <br>',
  t=t+'<input type="password" name="confirmasenhacad" required><br><br>',
  // t=t+'<script type="text/javascript"> function x(){var cli = new cliente(); cli.setNome(document.getElementById(nome));console.log(cli.getNome());} 	</script>',
  t=t+'<input type="submit" value="Me cadastrar">',
  t=t+'</form>',
  t=t+'</div>',
  t=t+'<h1>OU</h1>'
  t=t+'<div id="tabelacad">',
  t=t+'<h1>Servidor</h1>',
  t=t+'<form onsubmit="return cadastrarS();">',
  t=t+'Seu nome: <br>',
  t=t+'<input type="text" name="sprimeironomecad" id="nome" required> <br>',
  t=t+'Seu sobrenome: <br>',
  t=t+'<input type="text" name="ssobrenomecad" required> <br>',
  t=t+'Seu e-mail: <br>',
  t=t+'<input type="text" name="semailcad" placeholder="Ex.: ricardo@gmail.com" required> <br>',
  t=t+'Seu CEP: <br>',
  t=t+'<input type="number" name="scepcad" placeholder="xxxxx-xxx" required> <br>',
  t=t+'Seu telefone de contato: <br>',
  t=t+'<input type="number" name="stelcad" placeholder="(xx) x xxxx-xxxx" required> <br>',
  t=t+'Tipo de cadastro:<br>',
  t=t+'<input list="tipo" name="tipocad" required><datalist id="tipo">',
  t=t+'<option value="DJ">DJ</option>',
  t=t+'<option value="Assador">Assador</option>',
  t=t+'<option value="Barman">Barman</option>',
  t=t+'</datalist><br>',
  t=t+'Crie uma senha: <br>',
  t=t+'<input type="password" name="ssenhacad" required> <br>',
  t=t+'Confirme sua senha: <br>',
  t=t+'<input type="password" name="sconfirmasenhacad" required><br><br>',
  // t=t+'<script type="text/javascript"> function x(){var cli = new cliente(); cli.setNome(document.getElementById(nome));console.log(cli.getNome());} 	</script>',
  t=t+'<input type="submit" value="Me cadastrar">',
  t=t+'</form>',
  t=t+'</div>',
  t=t+'</div>'
$xy.innerHTML=t;
};
