var escentroid= function() {
  var $xy=document.querySelector('.conteudo_central'),
  t='<div class="conteudocentro">',
  t=t+'<ul>',
  // t=t+'<li><img src="imagens/assador.jpg" width="150px" height="150px" />',
  // t=t+'<div id="poder_ass">',
  // t=t+'<p>Avaliação</p>',
  // t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  // t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  // t=t+'<img src="imagens/scouterblack.png" width="30px" height="30px"/>',
  // t=t+'<img src="imagens/scouterblack.png" width="30px" height="30px"/>',
  // t=t+'<img src="imagens/scouterblack.png" width="30px" height="30px"/>',
  // t=t+'</div>',
  // t=t+'</li>',
  // t=t+'<li><img src="imagens/barman.jpg" width="150px" height="150px" />',
  // t=t+'<div id="poder_barman">',
  // t=t+'<p>Avaliação</p>',
  // t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  // t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  // t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  // t=t+'<img src="imagens/scouterblack.png" width="30px" height="30px"/>',
  // t=t+'<img src="imagens/scouterblack.png" width="30px" height="30px"/>',
  // t=t+'</div>',
  // t=t+'</li>',
  t=t+'<li onclick=anima(escxt)><img src="imagens/caixa.jpg" width="150px" height="150px" />',
  t=t+'<div id="poder_caixa">',
  t=t+'<p>Avaliação</p>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouterblack.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouterblack.png" width="30px" height="30px"/>',
  t=t+'</div>',
  t=t+'</li>',
  t=t+'<li onclick=anima(esks)><img src="imagens/kitchop.jpg" width="150px" height="150px" />',
  t=t+'<div id="poder_chop">',
  t=t+'<p>Avaliação</p>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouterblack.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouterblack.png" width="30px" height="30px"/>',
  t=t+'</div>',
  t=t+'</li>',
  t=t+'<li onclick=anima(essons)><img src="imagens/som.jpg" width="150px" height="150px" />',
  t=t+'<div id="poder_som">',
  t=t+'<p>Avaliação</p>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouterblack.png" width="30px" height="30px"/>',
  t=t+'</div>',
  // t=t+'</li>',
  // t=t+'<li><img src="imagens/dj.png" width="150px" height="150px" />',
  // t=t+'<div id="poder_dj">',
  // t=t+'<p>Avaliação</p>',
  // t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  // t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  // t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  // t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  // t=t+'<img src="imagens/scouterblack.png" width="30px" height="30px"/>',
  // t=t+'</div>',
  // t=t+'</li>',
  t=t+'</ul>',
  t=t+'</div>'
  $xy.innerHTML=t;
};
