function escrodape(n) {
  if(n==1){
    var $xy = document.querySelector('.footerdiv'),
    t2='',
    t2=t2+'<nav class="footer-links1"><h1>Categorias</h1><ul>',
    t2=t2+'<li><a href="javascript:anima(escassadores)">Assador</a></li>',
    t2=t2+'<li><a href="javascript:anima(esbarmans)">Barman</a></li>',
    t2=t2+'<li><a href="javascript:anima(escxt)">Caixa Termica</a></li>',
    t2=t2+'<li><a href="javascript:anima(esks)">Kitchop</a></li>',
    t2=t2+'<li><a href="javascript:anima(esdjs)">Som</a></li>',
    t2=t2+'<li><a href="javascript:anima(essons)">dj</a></li>',
    t2=t2+'</ul>',
    t2=t2+'</nav>',
    t2=t2+'<nav class="footer-links2">',
    t2=t2+'<h1>Institucional</h1>',
    t2=t2+'<ul>',
    t2=t2+'<li><a href="javascript:anima(esquemsomos)">Quem Somos</a></li>',
    t2=t2+'<li><a href="javascript:anima(esobjs)">Objetivos</a></li>',
    t2=t2+'<li><a href="javascript:anima(estermo)">Termos de Uso</a></li>',
    t2=t2+'<li><a href="javascript:anima(esajuda)">Ajuda</a></li>',
    t2=t2+'<li><a href="javascript:anima(esfalecom)">Fale Conosco</a></li>',
    t2=t2+'<li><a href="documentação/referencia.pdf">Sites de referência</a></li>',
    t2=t2+'</ul>',
    t2=t2+'</nav>',
    t2=t2+'<nav class="footer-links3">',
    t2=t2+'<h1>Desenvolvedores: <a href="#"><br>Olivir && João</a> </h1>',
    t2=t2+'<ul>',
    t2=t2+'<li><a href="javascript:anima(esfalecom)"><img src="imagens/Facebook.png" width="50px"height="50px" /></a></li>',
    t2=t2+'<li><a href="javascript:anima(esfalecom)"><img src="imagens/twitter.png" width="65px"height="65px" /></a></li>',
    t2=t2+'<li><a href="javascript:anima(esfalecom)"><img src="imagens/Github.png" width="40px"height="40px"/></a></li>',
    t2=t2+'</ul>',
    t2=t2+'<p>Hype © Direitos reservados. 2017</p>',
    t2=t2+'</nav>';
  }
  if(n==2){
    var $xy = document.querySelector('.footerdiv'),
    t2='',
    t2=t2+'<nav class="footer-links1"><h1>Categorias</h1><ul>',
    t2=t2+'<li><a href="javascript:escoElemento()">Assador</a></li>',
    t2=t2+'<li><a href="javascript:escoElemento()">Barman</a></li>',
    t2=t2+'<li><a href="javascript:escoElemento()">Caixa Termica</a></li>',
    t2=t2+'<li><a href="javascript:escoElemento()">Kitchop</a></li>',
    t2=t2+'<li><a href="javascript:escoElemento()">Som</a></li>',
    t2=t2+'<li><a href="javascript:escoElemento()">dj</a></li>',
    t2=t2+'</ul>',
    t2=t2+'</nav>',
    t2=t2+'<nav class="footer-links2">',
    t2=t2+'<h1>Institucional</h1>',
    t2=t2+'<ul>',
    t2=t2+'<li><a href="javascript:escoElemento()">Quem Somos</a></li>',
    t2=t2+'<li><a href="javascript:escoElemento()">Objetivos</a></li>',
    t2=t2+'<li><a href="javascript:escoElemento()">Termos de Uso</a></li>',
    t2=t2+'<li><a href="javascript:escoElemento()">Ajuda</a></li>',
    t2=t2+'<li><a href="javascript:escoElemento()">Fale Conosco</a></li>',
    t2=t2+'<li><a href="../documentação/referencia.pdf">Sites de referência</a></li>',
    t2=t2+'</ul>',
    t2=t2+'</nav>',
    t2=t2+'<nav class="footer-links3">',
    t2=t2+'<h1>Desenvolvedores: <a href="#"><br>Olivir && João</a> </h1>',
    t2=t2+'<ul>',
    t2=t2+'<li><a href="javascript:escoElemento()"><img src="../imagens/Facebook.png" width="50px"height="50px" /></a></li>',
    t2=t2+'<li><a href="javascript:escoElemento()"><img src="../imagens/twitter.png" width="65px"height="65px" /></a></li>',
    t2=t2+'<li><a href="javascript:escoElemento()"><img src="../imagens/Github.png" width="40px"height="40px"/></a></li>',
    t2=t2+'</ul>',
    t2=t2+'<p>Hype © Direitos reservados. 2017</p>',
    t2=t2+'</nav>';
  };
  $xy.innerHTML=t2;
}
