function escrodape(n) {
  if(n==1){
    var $xy = document.querySelector('.footerdiv'),
    t2='',
    t2=t2+'<nav class="footer-links1"><h1>Categorias</h1><ul>',
    t2=t2+'<li><a href="#">Assador</a></li>',
    t2=t2+'<li><a href="#">Barman</a></li>',
    t2=t2+'<li><a href="#">Caixa Termica</a></li>',
    t2=t2+'<li><a href="#">Kitchop</a></li>',
    t2=t2+'<li><a href="#">Som</a></li>',
    t2=t2+'<li><a href="#">dj</a></li>',
    t2=t2+'</ul>',
    t2=t2+'</nav>',
    t2=t2+'<nav class="footer-links2">',
    t2=t2+'<h1>Institucional</h1>',
    t2=t2+'<ul>',
    t2=t2+'<li><a href="#">Quem Somos</a></li>',
    t2=t2+'<li><a href="#">Objetivos</a></li>',
    t2=t2+'<li><a href="#">Termos de Uso</a></li>',
    t2=t2+'<li><a href="#">Ajuda</a></li>',
    t2=t2+'<li><a href="#">Fale Conosco</a></li>',
    t2=t2+'<li><a href="referencia.pdf">Sites de referência</a></li>',
    t2=t2+'</ul>',
    t2=t2+'</nav>',
    t2=t2+'<nav class="footer-links3">',
    t2=t2+'<h1>Desenvolvedores: <a href="#"><br>Olivir && João</a> </h1>',
    t2=t2+'<ul>',
    t2=t2+'<li><a href="#"><img src="imagens/Facebook.png" width="50px"height="50px" /></a></li>',
    t2=t2+'<li><a href="#"><img src="imagens/twitter.png" width="65px"height="65px" /></a></li>',
    t2=t2+'<li><a href="#"><img src="imagens/Github.png" width="40px"height="40px"/></a></li>',
    t2=t2+'</ul>',
    t2=t2+'<p>Hype © Direitos reservados. 2017</p>',
    t2=t2+'</nav>';
  }
  if(n==2){
    var $xy = document.querySelector('.footerdiv'),
    t2='',
    t2=t2+'<nav class="footer-links1"><h1>Categorias</h1><ul>',
    t2=t2+'<li><a href="#">Assador</a></li>',
    t2=t2+'<li><a href="#">Barman</a></li>',
    t2=t2+'<li><a href="#">Caixa Termica</a></li>',
    t2=t2+'<li><a href="#">Kitchop</a></li>',
    t2=t2+'<li><a href="#">Som</a></li>',
    t2=t2+'<li><a href="#">dj</a></li>',
    t2=t2+'</ul>',
    t2=t2+'</nav>',
    t2=t2+'<nav class="footer-links2">',
    t2=t2+'<h1>Institucional</h1>',
    t2=t2+'<ul>',
    t2=t2+'<li><a href="#">Quem Somos</a></li>',
    t2=t2+'<li><a href="#">Objetivos</a></li>',
    t2=t2+'<li><a href="#">Termos de Uso</a></li>',
    t2=t2+'<li><a href="#">Ajuda</a></li>',
    t2=t2+'<li><a href="#">Fale Conosco</a></li>',
    t2=t2+'<li><a href="../documentação/referencia.pdf">Sites de referência</a></li>',
    t2=t2+'</ul>',
    t2=t2+'</nav>',
    t2=t2+'<nav class="footer-links3">',
    t2=t2+'<h1>Desenvolvedores: <a href="#"><br>Olivir && João</a> </h1>',
    t2=t2+'<ul>',
    t2=t2+'<li><a href="#"><img src="../imagens/Facebook.png" width="50px"height="50px" /></a></li>',
    t2=t2+'<li><a href="#"><img src="../imagens/twitter.png" width="65px"height="65px" /></a></li>',
    t2=t2+'<li><a href="#"><img src="../imagens/Github.png" width="40px"height="40px"/></a></li>',
    t2=t2+'</ul>',
    t2=t2+'<p>Hype © Direitos reservados. 2017</p>',
    t2=t2+'</nav>';
  };
  $xy.innerHTML=t2;
}
