var infson = function (){
  var $xy = document.querySelector('.conteudo_central'),
  t='<div class="conteudocentro">',
  t=t+'<h1>Sobre SOM Hype</h1>',
  t=t+'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.Pellentesque lobortis, sapien sit amet placerat euismod, nibh ex ornare justo, eu porttitor augue arcu vitae est. Pellentesque tempor velit sit amet nibh tempus dapibus. Fusce viverra sit amet ante in aliquam. Maecenas in malesuada neque, eu tempus turpis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut sit amet interdum orci. Sed mollis diam eget varius ultrices. Nulla quis pulvinar ipsum, sit amet condimentum enim. Praesent efficitur pulvinar ullamcorper. Vivamus tempus dapibus risus, vel cursus urna gravida ac. Proin congue fermentum fringilla.</p></br>'
  t=t+'<p>Nulla facilisi. Nulla eros velit, convallis vitae dictum et, tristique ac sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse rutrum lectus id massa facilisis dapibus. Phasellus id metus rutrum, fermentum diam tincidunt, bibendum elit. Curabitur fermentum hendrerit nisl, id tempus lorem molestie quis. Suspendisse in enim nibh. Aenean vel felis lorem. Vestibulum euismod, orci at auctor ultrices, metus diam porttitor dui, ac finibus arcu velit at arcu. Pellentesque auctor erat eu sodales dignissim.</p></br>'
  t=t+'<p>Maecenas faucibus lacinia sem eu rhoncus. Duis arcu elit, laoreet id scelerisque vitae, pretium vitae sapien. Vivamus et dui scelerisque, rutrum urna id, convallis mauris. Etiam facilisis finibus elit a hendrerit. Pellentesque ac venenatis magna. Donec dignissim dui non libero feugiat, in consequat nisi tempor. Nam tristique, tellus id eleifend ullamcorper, elit velit rutrum ligula, eu porta libero justo sit amet enim. Suspendisse iaculis dignissim magna. Pellentesque congue vitae neque sed consequat. Etiam magna neque, sagittis ut elementum et, consequat ac magna. Fusce lacinia risus ornare tempus finibus.</p>'
  t=t+'</div>',
  $xy.innerHTML=t;
}
