function escxt() {
  var $xy = document.querySelector('.conteudo_central'),
  t='',
  t=t+'<div class="conteudocentro">',
  t=t+'<ul>',
  t=t+'<li onclick=anima(esfalecom)><img src="imagens/caixa.jpg" width="150px" height="150px" />',
  t=t+'<div id="poder_ass">',
  t=t+'<p>Avaliação</p>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouterblack.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouterblack.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouterblack.png" width="30px" height="30px"/>',
  t=t+'</div>',
  t=t+'</li>',
  t=t+'<li onclick=anima(esfalecom)><img src="imagens/caixa1.jpg" width="150px" height="150px" />',
  t=t+'<div id="poder_barman">',
  t=t+'<p>Avaliação</p>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouterblack.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouterblack.png" width="30px" height="30px"/>',
  t=t+'</div>',
  t=t+'</li>',
  t=t+'<li onclick=anima(esfalecom)><img src="imagens/caixa2.jpg" width="150px" height="150px" />',
  t=t+'<div id="poder_caixa">',
  t=t+'<p>Avaliação</p>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouterblack.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouterblack.png" width="30px" height="30px"/>',
  t=t+'</div>',
  t=t+'</li>',
  t=t+'<li onclick=anima(esfalecom)><img src="imagens/caixa3.jpg" width="150px" height="150px" />',
  t=t+'<div id="poder_chop">',
  t=t+'<p>Avaliação</p>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouterblack.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouterblack.png" width="30px" height="30px"/>',
  t=t+'</div>',
  t=t+'</li>',
  t=t+'<li onclick=anima(esfalecom)><img src="imagens/caixa4.jpg" width="150px" height="150px" />',
  t=t+'<div id="poder_som">',
  t=t+'<p>Avaliação</p>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouterblack.png" width="30px" height="30px"/>',
  t=t+'</div>',
  t=t+'</li>',
  t=t+'<li onclick=anima(esfalecom)><img src="imagens/caixa5.jpg" width="150px" height="150px" />',
  t=t+'<div id="poder_dj">',
  t=t+'<p>Avaliação</p>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouter.png" width="30px" height="30px"/>',
  t=t+'<img src="imagens/scouterblack.png" width="30px" height="30px"/>',
  t=t+'</div>',
  t=t+'</li>',
  t=t+'</ul>',
  t=t+'</div>'
  $xy.innerHTML=t;
}
